# Generated by Django 5.1.4 on 2024-12-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='prompt',
            field=models.TextField(default=1, verbose_name='Промт истрории для персонажа'),
            preserve_default=False,
        ),
    ]
